#ifndef DUNGEONS_AND_DRAGONS_CONSTANTS_HPP
#define DUNGEONS_AND_DRAGONS_CONSTANTS_HPP

// Player
#define MAX_HEALTH 50

#define MAGE_INTELLECT 40
#define MAGE_STRENGTH 10

#define WARRIOR_INTELLECT 10
#define WARRIOR_STRENGTH 40

// Dragon
#define INITIAL_DRAGON_STRENGTH 25
#define INITIAL_DRAGON_INTELLECT 25
#define INITIAL_DRAGON_HEALTH 50


#endif //DUNGEONS_AND_DRAGONS_CONSTANTS_HPP
